import json
import uuid
from pathlib import Path
from tera.domain import TeraSchema
from tera.contracts import TeraWriter

class PostmanWriter(TeraWriter):
    """
    Concrete implementation of TeraWriter.
    Recieves the Schema, converts to Postman Collection (v2.1).
    """

    def __init__(self, output_path: Path):
        self.output_path = output_path

    def write(self, schema: TeraSchema) -> None:
        collection = {
            "info": {
                "name": schema.api.name,
                "description": schema.api.description or "Generated by Tera CLI",
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
            },
            "item": [],
            "variable": [
                {
                    "key": "base_url",
                    "value": "http://localhost:5000",
                    "type": "string"
                }
            ]
        }

        for ep in schema.endpoints:
            clean_path = ep.path.replace("{", ":").replace("}", "")
            path_segments = [p for p in clean_path.split("/") if p]

            body_config = None
            if ep.body:
                example_data = {field.name: field.type for field in ep.body}
                body_config = {
                    "mode": "raw",
                    "raw": json.dumps(example_data, indent=2),
                    "options": {
                        "raw": {
                            "language": "json"
                        }
                    }
                }

            item = {
                "name": f"{ep.method} {ep.path}",
                "request": {
                    "method": ep.method,
                    "header": [],
                    "url": {
                        "raw": "{{base_url}}" + clean_path,
                        "host": ["{{base_url}}"],
                        "path": path_segments,
                        "variable": []
                    },
                    "description": ep.description or ep.summary
                }
            }

            if body_config:
                item["request"]["body"] = body_config
            collection["item"].append(item)

        with open(self.output_path, "w", encoding="utf-8") as f:
            json.dump(collection, f, indent=2, ensure_ascii=False)