# Tera CLI Configuration File (.teraconfig.toml)
# Documentation: https://github.com/vichsort/tera-cli

# Default import string for 'tera scan'
# target = "app:app"

# Default path to output generated for 'tera build'
# output = "openapi.json"

# API Title (overrides yaml if set)
title = "My Project API"

# Linter configuration
[lint]
# List of rules to ignore (Errors)
# ignore = ["missing_description", "unsafe_write_operation"]