from typing import Any, Dict, cast
from tera.contracts import TeraDriver
from tera.domain import TeraSchema
from tera.drivers.openapi_driver import OpenApiDriver
from tera.drivers.inspection.loader import load_app_instance
from tera.exceptions import TeraError


class FastApiDriver(TeraDriver):
    """
    Driver capable of reading a FastAPI / Starlette application via introspection.
    Extracts the schema generated by app.openapi() and converts it into a canonical TeraSchema.
    """

    def __init__(self, app_source: Any) -> None:
        self.source: Any = app_source

    def load(self) -> TeraSchema:
        app_obj: Any
        if isinstance(self.source, str):
            try:
                app_obj = load_app_instance(self.source)
            except Exception as e:
                raise TeraError(
                    "FastAPI Load Error",
                    f"Could not load application from '{self.source}': {e}",
                )
        else:
            app_obj = self.source

        # Handle application factory pattern if a callable is returned without .openapi()
        if callable(app_obj) and not hasattr(app_obj, "openapi"):
            try:
                app_obj = app_obj()
            except Exception as e:
                raise TeraError(
                    "FastAPI Factory Error",
                    f"Could not call application factory '{self.source}': {e}",
                )

        openapi_method: Any = getattr(app_obj, "openapi", None)
        if not callable(openapi_method):
            raise TeraError(
                "Invalid FastAPI App",
                f"The target '{self.source}' does not expose an .openapi() callable method.",
            )

        try:
            schema_data: Any = openapi_method()
        except Exception as e:
            raise TeraError(
                "OpenAPI Generation Error",
                f"Error calling app.openapi(): {e}",
            )

        if not isinstance(schema_data, dict):
            raise TeraError(
                "Invalid OpenAPI Schema",
                f"app.openapi() did not return a dictionary (got {type(schema_data).__name__}).",
            )

        typed_schema = cast(Dict[str, Any], schema_data)
        driver = OpenApiDriver(typed_schema)
        return driver.load()

