import re
from typing import Any, List, Set
from tera.domain.models import (
    TeraSchema, 
    ApiConfig, 
    Endpoint, 
    EndpointParams, 
    ParamField, 
    EndpointResponses, 
    ResponseSuccess
)
from tera.drivers.inspection import loader, parser

class FlaskAppDriver:
    """
    Driver capable of reading an Flask app via instrospection.
    Translates Routes and View Functions into TeraSchema.
    """
    def __init__(self, app_import_string: str):
        self.import_string = app_import_string

    def load(self) -> TeraSchema:
        app = loader.load_app_instance(self.import_string)
        
        endpoints: List[Endpoint] = []
        
        for rule in app.url_map.iter_rules():
            if rule.endpoint == 'static':
                continue

            for method in rule.methods:
                if method in ['HEAD', 'OPTIONS']:
                    continue

                endpoint = self._process_rule(app, rule, method)
                endpoints.append(endpoint)

        return TeraSchema(
            api=ApiConfig(
                name=getattr(app, 'name', 'Flask App'),
                version="1.0.0",
                description="Auto-generated by Tera"
            ),
            endpoints=endpoints
        )

    def _process_rule(self, app: Any, rule: Any, method: str) -> Endpoint:
        """Transforms a Rule in an Endpoint"""  
        view_func = app.view_functions[rule.endpoint]
        doc_info = parser.parse_docstring(view_func)
        sig_info = parser.parse_signature(view_func)
        path_openapi = self._convert_flask_path_to_openapi(str(rule))
        path_vars: Set[str] = set(rule.arguments)     
        query_params: List[ParamField] = []
        path_params: List[ParamField] = []

        for name, type_hint in sig_info.parameters.items():
            
            example_value = self._get_example_for_type(type_hint)
            
            field = ParamField(
                name=name,
                example=example_value,
                required=True,
                description=None
            )

            if name in path_vars:
                path_params.append(field)
            else:
                field.required = False
                query_params.append(field)

        return Endpoint(
            path=path_openapi,
            method=method,
            summary=doc_info.summary,
            description=doc_info.description,
            params=EndpointParams(
                path=path_params,
                query=query_params
            ),
            responses=EndpointResponses(
                success=ResponseSuccess(
                    status=200,
                    example={"message": "Success"}
                )
            )
        )

    def _convert_flask_path_to_openapi(self, flask_path: str) -> str:
        """
        Converts '/user/<int:id>' to '/user/{id}'
        Regex:
        <       : Start
        (?:     : Non-capturing group (optional)
          \w+:  : Text followed by colon (e.g., 'int:')
        )?      : Non-capturing group (optional)
        (\w+)   : Variable name (captured)
        >       : End
        """
        return re.sub(r"<(?:\w+:)?(\w+)>", r"{\1}", flask_path)

    def _get_example_for_type(self, type_hint: Any) -> Any:
        """Generates an example based on the type hint."""
        if type_hint is int:
            return 0
        if type_hint is float:
            return 0.0
        if type_hint is bool:
            return True
        if type_hint is dict:
            return {}
        if type_hint is list:
            return []
        return "string"